apiVersion: v1
kind: Namespace
metadata:
  name: ci-cd
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb
  namespace: ci-cd
spec:
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      nodeSelector:
        kubernetes.io/hostname: geeko-dev-master-a1d4c60c-dwjb
      containers:
        - name: mongodb
          image: mongo:4.4.5
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: mongouser
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: mongopwd         
---
apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: ci-cd
spec:
  selector:
    app: mongodb
  ports:
    - port: 27017
      targetPort: 27017
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: ci-cd
spec:
  replicas: 1
  selector:
    matchLabels:
      app: api
  template:
    metadata:  
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "8080"        
      labels:
        app: api
    spec:
      nodeSelector:
        kubernetes.io/hostname: geeko-dev-master-a1d4c60c-dwjb
      containers:
        - name: api
          image: gabriellins/api-produto:{{tag}}
          ports: 
          - containerPort: 8080
          env: 
          - name: MONGODB_URI
            value: mongodb://mongouser:mongopwd@mongodb-service:27017/admin
--- 
apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: ci-cd
spec:
  selector:
    app: api
  ports:
    - port: 80
      targetPort: 8080
      nodePort: 30316
  type: NodePort